server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: lb://auth-service
              predicates:
                - Path=/auth-service/**
              filters:
                - RewritePath=/auth-service/(?<remaining>.*), /${remaining}

            - id: zone-service
              uri: lb://zone-service
              predicates:
                - Path=/zone-service/**
              filters:
                - AuthenticationFilter
                - RewritePath=/zone-service/(?<remaining>.*), /${remaining}

            - id: automation-service
              uri: lb://automation-service
              predicates:
                - Path=/automation-service/**
              filters:
                - AuthenticationFilter
                - RewritePath=/automation-service/(?<remaining>.*), /${remaining}

            - id: crop-service
              uri: lb://crop-service
              predicates:
                - Path=/crop-service/**
              filters:
                - AuthenticationFilter
                - RewritePath=/crop-service/(?<remaining>.*), /${remaining}

            - id: sensor-telemetry-service
              uri: lb://sensor-telemetry-service
              predicates:
                - Path=/sensor-telemetry-service/**
              filters:
                - AuthenticationFilter
                - RewritePath=/sensor-telemetry-service/(?<remaining>.*), /${remaining}

          globalcors:
            cors-configurations:
              '[/**]':
                allowed-origins:
                  - "http://localhost:3000"
                allowed-methods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - OPTIONS
                allowed-headers: "*"
                allow-credentials: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG