server:
  port: 8083
  servlet:
    context-path: /automation-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: automation-service