server:
  port: 8082
  servlet:
    context-path: /sensor-telemetry-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: sensor-telemetry-service