server:
  port: 8081
  servlet:
    context-path: /zone-service

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: mysql
    url: jdbc:mysql://localhost:3306/agms_zone_db?createDatabaseIfNotExist=true
    hikari:
      maximum-pool-size: 15

  jpa:
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
